version: "3.4"

services:

  postgres:
    container_name: coding-assessment-nodejs_postgres
    image: postgres:12.14
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database

  backend:
    container_name: coding-assessment-nodejs
    image: coding-assessment-nodejs
    build:
      context: .
      target: app_node
    volumes:
      - ./:/srv/app
    ports:
      - "9229:9229"
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://user:password@postgres:5432/database?serverVersion=12.14
      APP_PORT: 3000
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    command: "npm run start:dev"
